---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch admin.conf from master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/admin.conf
        flat: yes
      delegate_to: master-01

- hosts: workers
  become: yes
  tasks:
    - name: Copy admin.conf to workers
      copy:
        src: /tmp/admin.conf
        dest: /home/admin-kube/.kube/config
        owner: admin-kube
        group: admin-kube
        mode: '0600'
