---
- name: Deploy Kubernetes Cluster on Rocky Linux 9
  hosts: kubernetes
  become: yes
  gather_facts: yes
  serial: 1
  
  pre_tasks:
    - name: Verify Rocky Linux 9
      assert:
        that:
          - ansible_distribution == "Rocky"
          - ansible_distribution_major_version == "9"
        fail_msg: "This playbook is designed for Rocky Linux 9 only"

  roles:
    - common
    - container-runtime
    - kubernetes

- name: Initialize Kubernetes Cluster
  hosts: masters
  become: yes
  gather_facts: no
  serial: 1
  
  roles:
    - cluster-init

- name: Join Worker Nodes to Cluster
  hosts: workers
  become: yes
  gather_facts: no
  serial: 1
  
  roles:
    - worker-join

- name: Post-deployment verification
  hosts: masters[0]
  become: yes
  gather_facts: no
  
  tasks:
    - name: Display cluster status
      shell: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cluster_status
    
    - name: Show cluster information
      debug:
        msg: "{{ cluster_status.stdout_lines }}"
    
    - name: Display cluster info
      shell: kubectl cluster-info
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cluster_info
    
    - name: Show cluster info
      debug:
        msg: "{{ cluster_info.stdout_lines }}"
    
    - name: Verify all nodes are ready
      shell: kubectl get nodes --no-headers | grep -v Ready | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: nodes_not_ready
      failed_when: nodes_not_ready.stdout != "0"